
services:
  flask_dev:
    build:
      context: services/flask
      dockerfile: Dockerfile_dev
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/flask/:/usr/src/app/
    ports:
      - '5001:5000'
    env_file:
      - ./.env_dev
    depends_on:
        - postgres_dev
  postgres_dev:
    build:
      context: services/postgres
      dockerfile: Dockerfile_dev
    volumes:
    - postgres_data_dev:/var/lib/postgresql/data/
    env_file:
      - ./.env_dev

volumes:
  postgres_data_dev:
