services:
  flask_prod:
    build:
      context: services/flask
      dockerfile: Dockerfile_prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
      - ./.env_prod
    environment:
      - CONTAINER_ROLE=flask
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - MAIL_SENDING_ADDRESS_FILE=/run/secrets/mail_sending_address
      - MAIL_SENDING_PASSWORD_FILE=/run/secrets/mail_sending_password
      - MAIL_SMTP_PORT_FILE=/run/secrets/mail_smtp_port
      - MAIL_SMTP_SERVER_FILE=/run/secrets/mail_smtp_server
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
      - mail_sending_address
      - mail_sending_password
      - mail_smtp_port
      - mail_smtp_server

  postgres_prod:
    build:
      context: ./services/postgres
      dockerfile: Dockerfile_prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    environment:
      - CONTAINER_ROLE=postgres
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_ROOT_PASSWORD_FILE=/run/secrets/postgres_root_password
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
      - postgres_root_password
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile_prod
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - flask_prod

  certbot:
    build:
      context: ./services/certbot
      dockerfile: Dockerfile_prod
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw


secrets:
  postgres_user:
    file: /home/deployer/dock_secrets/postgres_user.txt

  postgres_password:
    file: /home/deployer/dock_secrets/postgres_password.txt

  postgres_db:
    file: /home/deployer/dock_secrets/postgres_db.txt

  postgres_root_password:
    file: /home/deployer/dock_secrets/postgres_root_password.txt

  mail_sending_address:
    file: /home/deployer/dock_secrets/mail_sending_address.txt

  mail_sending_password:
    file: /home/deployer/dock_secrets/mail_sending_password.txt

  mail_smtp_port:
    file: /home/deployer/dock_secrets/mail_smtp_port.txt

  mail_smtp_server:
    file: /home/deployer/dock_secrets/mail_smtp_server.txt

volumes:
  postgres_data_prod: