FROM nginx:1.25

# Install Certbot
RUN apt-get update && apt-get install -y certbot

# Remove default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom Nginx configuration
COPY conf/nginx.conf /etc/nginx/conf.d

# Create directory for Certbot challenges
#RUN mkdir -p /usr/share/nginx/html/.well-known/acme-challenge
#RUN touch /usr/share/nginx/html/.well-known/acme-challenge/test_file.txt
#RUN echo "Hello from usr/share" >  /usr/share/nginx/html/.well-known/acme-challenge/test_file.txt
