name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push Flask service
        uses: docker/build-push-action@v6
        with:
          context: ./services/flask
          file: ./services/flask/Dockerfile_prod
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}-flask:latest
      -
        name: Build and push Postgres service
        uses: docker/build-push-action@v6
        with:
          context: ./services/postgres
          file: ./services/postgres/Dockerfile_prod
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}-postgres:latest
